### ISSUE TITLE
[Bug] Organization permissions issues

### ISSUE THREAD

**Issue by tcatlas** [gnmyt/Nexterm#976]
### General

- [x] I have updated to the latest version of Nexterm.
- [x] My bug has not been reported yet.

### The Bug

- Admins that are members of an organization (but did not create it) cannot invite other users to the organization. The button doesn't appear.
- In this scenario, the members list is also blank.
  - The original user that created the organization was deleted.
- Admins cannot see organizations they are not members of and/or did not create.

<img width="887" height="216" alt="Image" src="https://github.com/user-attachments/assets/fb6bfc85-9625-4aeb-bc2c-037b537c5b34" />

<img width="925" height="429" alt="Image" src="https://github.com/user-attachments/assets/cd9a1163-ac62-419d-b3ce-06abc0ced65f" />

### What device are you using to access the page?

In the browser

### Which operating system is your Nexterm instance running on?

Linux

**Comment by gnmyt** [comment]
Hi, I also ran into this issue yesterday when implementing #970. Are you running on the newest dev or stable build? Commit https://github.com/gnmyt/Nexterm/pull/970/changes/fe68d2211fb8eb67d8778b08f3542e3fb546e73e should also resolve this issue.

Note that you will either have to clear the database or just remove the old user from the organization_members table. The issue has been caused by old users not being deleted after they got removed from the system.

**Comment by tcatlas** [comment]
This is on newest stable, 1.0.8.

**Comment by gnmyt** [comment]
The issue should be fixed in the next version then. Commit https://github.com/gnmyt/Nexterm/commit/fe68d2211fb8eb67d8778b08f3542e3fb546e73e is not yet included in stable. Feel free to test again with the development release or as soon as the next 1.0.8 comes out. 

I'll mark this as resolved for now. If the issue still occurs in the newer versions, feel free to re-open.

**Comment by tcatlas** [comment]
On 1.0.9 using Nexterm Connector, the organization members list shows up correctly now. Looking at the database, I see the old user was deleted, however, my admin user (which is an SSO user) still cannot manage the organization the original admin created.

**Comment by tcatlas** [comment]
If you are saying this shouldn't be an issue going forward due to #970, I can just edit the database to set my user as the owner on the org.
